version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Install phase"
  build:
    commands:
      - echo "Build phase"
      # Clone the GitHub repository
      - git clone https://github.com/devmanvi/app1.git
      # Copy files from the cloned repository to S3 bucket
      - aws s3 cp app1 s3://code-app3/ --recursive
      - echo "Files copied to S3"
 artifacts:
  files:
    - '**/*'
  base-directory: codepipeline-us-east-1-459313849297
  name: build-artifact-name
  discard-paths: no